apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: modanisa-ba:0.0.1
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: mongoUri
            - name: TEST_MONGODB_URI
              value: mongoTestUri
            - name: PORT
              value: "3001"
          
